before_install:
  - git clone https://github.com/WordPress/WordPress
  - cd wp-content
  - cd plugins

language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
  
script: php script/unit.script.php
matrix:
  allow_failures:
    - php: '5.6'
    - php: hhvm
    - php: '7.0'
    - php: nightly
  fast_finish: true